services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: always
    ports: 
      - "8080:8080"
    command: ["-db-dsn=${MRS_DB_DSN}", "-grpc-address=recommender", "-jwt-secret=${JWT_SECRET_KEY}", "-kafka-address=${KAFKA_ADDRESS}", "-kafka-password-ssl=${KAFKA_PASSWORD_SSL}", "-kafka-username=${KAFKA_USERNAME}", "-kafka-password-user=${KAFKA_PASSWORD_USER}"]
    volumes:
      - ./backend/internal/kafka/cert:/app/cert
    depends_on:
      - db
      - migrate

  recommender:
    image: vladgrskkh/mrs-recommender:latest
    restart: always
    expose: 
      - "50051"
  
  db:
    image: postgres:18
    env_file:
      - ./backend/.env_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrs_user -d mrs"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql

  migrate:
    image: migrate/migrate
    env_file:
      - ./backend/.env
    depends_on:
        db:
          condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "${MRS_DB_DSN}",
      "up"
    ]
    volumes:
      - ./backend/migrations:/migrations

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./backend/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

volumes:
  pgdata: