services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: always
    ports: 
      - "8080:8080"
    command: ["-db-dsn=${MRS_DB_DSN}", "-smtp-mailer-api-key=${MAILERSEND_API_KEY}", "-smtp-sender=${SMTP_USERNAME}", "-grpc-address=recommender", "-jwt-secret=${JWT_SECRET_KEY}", "-kafka-topic=email", "-kafka-address=kafka1:9092,kafka2:9094,kafka3:9096"]
    depends_on:
      - db
      - migrate

  notification-service:
    build: ./notificationservice
    env_file:
      - ./notificationservice/.env
    expose:
      - "8085"
    restart: always
    command: ["-cfg=config_prod.toml"]
    depends_on:
       - api
       - kafka-ui

  recommender:
    image: vladgrskkh/mrs-recommender:latest
    restart: always
    expose: 
      - "50051"
  
  db:
    image: postgres:18
    env_file:
      - ./backend/.env_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrs_user -d mrs"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql

  migrate:
    image: migrate/migrate
    env_file:
      - ./backend/.env
    depends_on:
        db:
          condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "${MRS_DB_DSN}",
      "up"
    ]
    volumes:
      - ./backend/migrations:/migrations

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./backend/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  kafka1:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'YC4vByx5R66s7QJQyJiUNA' 
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9094:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'YC4vByx5R66s7QJQyJiUNA'
    volumes:
      - kafka2_data:/var/lib/kafka/data
    depends_on:
      - kafka1

  kafka3:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9096:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'YC4vByx5R66s7QJQyJiUNA'
    volumes:
      - kafka3_data:/var/lib/kafka/data
    depends_on:
      - kafka1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.0
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - 8082:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry

volumes:
  pgdata:
  kafka1_data:
  kafka2_data:
  kafka3_data: