---
services:
  api:
    image: vladgrskkh/mrs-api:latest
    env_file: [.env]
    restart: always
    expose: ['8080']
    command:
      - -env=production
      - -db-dsn=${MRS_DB_DSN}
      - -grpc-address=recommender
      - -jwt-secret=${JWT_SECRET_KEY}
      - -kafka-address=${KAFKA_ADDRESS}
      - -kafka-password-ssl=${KAFKA_PASSWORD_SSL}
      - -kafka-username=${KAFKA_USERNAME}
      - -kafka-password-user=${KAFKA_PASSWORD_USER}
      - -redis-address=${REDIS_ADDRESS}
      - -redis-password=${REDIS_PASSWORD}
      - -redis-username=${REDIS_USERNAME}
    depends_on: [db, migrate, redis]
    networks: [shared-network]
    volumes: [./cert:/app/cert]

  db:
    image: postgres:18
    env_file: [.env_db]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U mrs_user -d mrs]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [shared-network]
    volumes: [pgdata:/var/lib/postgresql]

  migrate:
    image: migrate/migrate
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    command: [-path, /migrations, -database, '${MRS_DB_DSND}', up]
    networks: [shared-network]
    volumes: [./migrations:/migrations]

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
      - ALLOW_EMPTY_PASSWORD=yes
    expose: ['6379']
    networks: [shared-network]
    volumes:
      - ./conf/redis.acl:/opt/bitnami/redis/mounted-etc/users.acl
      - redis-data:/data

  caddy:
    image: serfriz/caddy-duckdns:latest
    restart: unless-stopped
    env_file: [.env]
    ports: [80:80, 443:443]
    networks: [shared-network]
    volumes:
      - $PWD/conf/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [api]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes: [$PWD/conf/prometheus.yml:/etc/prometheus/prometheus.yml]
    expose: ['9090']
    networks: [shared-network]
    depends_on: [api]

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    env_file: [.env]
    volumes:
      - $PWD/conf/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    expose: ['3000']
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    networks: [shared-network]
    depends_on: [api, prometheus]

networks:
  shared-network:
    external: true

volumes:
  pgdata:
  redis_data:
  caddy_data:
  caddy_config:
  grafana-data:
