version: "3.9"

services:
  api:
    image: vladgrskkh/mrs-api:latest
    env_file:
      - .env
    restart: always
    ports: 
      - "80:8080"
    command: ["-db-dsn=${MRS_DB_DSN}", "-smtp-username=${SMTP_USERNAME}", "-smtp-password=${SMTP_PASSWORD}"]
    depends_on:
      - db
      - migrate
  
  db:
    image: postgres:18
    env_file:
      - .env_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    command: [
      "-path", "/migrations",
      "-database", "${MRS_DB_DSN}",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  pgdata:
