version: "3.9"

services:
  api:
    image: vladgrskkh/mrs-api:latest
    env_file:
      - .env
    restart: always
    ports: 
      - "8080:8080"
    command: ["-db-dsn=${MRS_DB_DSND}", "-smtp-username=${SMTP_USERNAMED}", "-smtp-password=${SMTP_PASSWORDD}"]
    depends_on:
      - db
      - migrate
  
  db:
    image: postgres:18
    env_file:
      - .env_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrs_user -d mrs"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    depends_on:
        db:
          condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "${MRS_DB_DSND}",
      "up"
    ]
    volumes:
      - ./migrations:/migrations

volumes:
  pgdata:
