---
services:
  notification:
    image: vladgrskkh/mrs-notification-service:latest
    command: [-cfg=config_prog.toml]
    depends_on:
      kafka1:
        condition: service_healthy
    volumes:
      - ./config_prod.toml:/app/config_prog.toml
      - ./.env:/app/.env
      - ./cert:/app/cert

  kafka1:
    image: confluentinc/cp-kafka:latest
    ports: [80:80]
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 10
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:80,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9091,EXTERNAL://${KAFKA_EXTERNAL_ADDRESS}:80
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL,CONTROLLER:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLIENT_LISTENER_NAME: EXTERNAL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME_1}"
        password="${KAFKA_PASSWORD_1}" user_${KAFKA_USERNAME_1}="${KAFKA_PASSWORD_1}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD_USER}";
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME_1}"
        password="${KAFKA_PASSWORD_1}" user_${KAFKA_USERNAME_1}="${KAFKA_PASSWORD_1}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD_USER}";
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME_1}"
        password="${KAFKA_PASSWORD_1}" user_${KAFKA_USERNAME_1}="${KAFKA_PASSWORD_1}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD_USER}";
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_CERTIFICATE_PASSWORD: ${KAFKA_CERT_PASSWORD}
      KAFKA_TLS_TYPE: JKS
      KAFKA_SUPER_USERS: User:${KAFKA_USERNAME_1}
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka1.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_PASSWORD}
      KAFKA_SSL_KEY_PASSWORD: ${KAFKA_KEY_PASSWORD}
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_PASSWORD}
      KAFKA_LISTENER_NAME_EXTERNAL_SSL_CLIENT_AUTH: required
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - ./keystore/kafka1.server.keystore.jks:/etc/kafka/secrets/kafka1.server.keystore.jks
      - ./truststore/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks
      - kafka1_data:/var/lib/kafka/data

    healthcheck:
      test: bash -c 'printf "" > /dev/tcp/127.0.0.1/9091; exit $$?;'
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports: [8080:8080]
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: mrs-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9091
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL: SASL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule
        required username="${KAFKA_USERNAME_1}" password="${KAFKA_PASSWORD_SSL}";
      DYNAMIC_CONFIG_ENABLED: true
      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: ${KAFKAUI_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKAUI_PASSWORD}
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: ${KAFKA_TRUSTSTORE_PASSWORD}

    volumes: [./truststore/kafka.truststore.jks:/kafka.truststore.jks:ro]
    depends_on: [kafka1]

    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  shared-network:
    external: true
volumes:
  kafka1_data:
