# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/predict/predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1/predict/predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import types_pb2 as common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v1/predict/predict.proto\x12\nv1.predict\x1a\x12\x63ommon/types.proto\"&\n\x10RecommendRequest\x12\x12\n\nmovieTitle\x18\x01 \x01(\t\"D\n\x11RecommendResponse\x12/\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x16.common.Recommendation2Z\n\x0eRecommendation\x12H\n\tRecommend\x12\x1c.v1.predict.RecommendRequest\x1a\x1d.v1.predict.RecommendResponseBNZLgithub.com/vladgrskkh/movie_recomendation_system/genproto/v1/predict;predictb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.predict.predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/vladgrskkh/movie_recomendation_system/genproto/v1/predict;predict'
  _globals['_RECOMMENDREQUEST']._serialized_start=60
  _globals['_RECOMMENDREQUEST']._serialized_end=98
  _globals['_RECOMMENDRESPONSE']._serialized_start=100
  _globals['_RECOMMENDRESPONSE']._serialized_end=168
  _globals['_RECOMMENDATION']._serialized_start=170
  _globals['_RECOMMENDATION']._serialized_end=260
# @@protoc_insertion_point(module_scope)
