// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: v1/predict/predict.proto

package predict

import (
	common "github.com/vladgrskkh/movie_recomendation_system/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieTitle    string                 `protobuf:"bytes,1,opt,name=movieTitle,proto3" json:"movieTitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_v1_predict_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_predict_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_v1_predict_predict_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

type RecommendResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Recommendations []*common.Recommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_v1_predict_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_predict_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_v1_predict_predict_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetRecommendations() []*common.Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_v1_predict_predict_proto protoreflect.FileDescriptor

const file_v1_predict_predict_proto_rawDesc = "" +
	"\n" +
	"\x18v1/predict/predict.proto\x12\n" +
	"v1.predict\x1a\x12common/types.proto\"2\n" +
	"\x10RecommendRequest\x12\x1e\n" +
	"\n" +
	"movieTitle\x18\x01 \x01(\tR\n" +
	"movieTitle\"U\n" +
	"\x11RecommendResponse\x12@\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x16.common.RecommendationR\x0frecommendations2Z\n" +
	"\x0eRecommendation\x12H\n" +
	"\tRecommend\x12\x1c.v1.predict.RecommendRequest\x1a\x1d.v1.predict.RecommendResponseBNZLgithub.com/vladgrskkh/movie_recomendation_system/genproto/v1/predict;predictb\x06proto3"

var (
	file_v1_predict_predict_proto_rawDescOnce sync.Once
	file_v1_predict_predict_proto_rawDescData []byte
)

func file_v1_predict_predict_proto_rawDescGZIP() []byte {
	file_v1_predict_predict_proto_rawDescOnce.Do(func() {
		file_v1_predict_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_predict_predict_proto_rawDesc), len(file_v1_predict_predict_proto_rawDesc)))
	})
	return file_v1_predict_predict_proto_rawDescData
}

var file_v1_predict_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_predict_predict_proto_goTypes = []any{
	(*RecommendRequest)(nil),      // 0: v1.predict.RecommendRequest
	(*RecommendResponse)(nil),     // 1: v1.predict.RecommendResponse
	(*common.Recommendation)(nil), // 2: common.Recommendation
}
var file_v1_predict_predict_proto_depIdxs = []int32{
	2, // 0: v1.predict.RecommendResponse.recommendations:type_name -> common.Recommendation
	0, // 1: v1.predict.Recommendation.Recommend:input_type -> v1.predict.RecommendRequest
	1, // 2: v1.predict.Recommendation.Recommend:output_type -> v1.predict.RecommendResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_predict_predict_proto_init() }
func file_v1_predict_predict_proto_init() {
	if File_v1_predict_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_predict_predict_proto_rawDesc), len(file_v1_predict_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_predict_predict_proto_goTypes,
		DependencyIndexes: file_v1_predict_predict_proto_depIdxs,
		MessageInfos:      file_v1_predict_predict_proto_msgTypes,
	}.Build()
	File_v1_predict_predict_proto = out.File
	file_v1_predict_predict_proto_goTypes = nil
	file_v1_predict_predict_proto_depIdxs = nil
}
