// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	data "github.com/vladgrskkh/movie_recomendation_system/internal/data"
)

// moviesInterface is an autogenerated mock type for the moviesInterface type
type moviesInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *moviesInterface) Delete(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *moviesInterface) Get(_a0 int64) (*data.Movie, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*data.Movie, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) *data.Movie); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0, _a1, _a2
func (_m *moviesInterface) GetAll(_a0 string, _a1 []string, _a2 data.Filters) ([]*data.Movie, data.Metadata, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*data.Movie
	var r1 data.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(string, []string, data.Filters) ([]*data.Movie, data.Metadata, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, []string, data.Filters) []*data.Movie); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string, data.Filters) data.Metadata); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(data.Metadata)
	}

	if rf, ok := ret.Get(2).(func(string, []string, data.Filters) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: _a0
func (_m *moviesInterface) Insert(_a0 *data.Movie) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Movie) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *moviesInterface) Update(_a0 *data.Movie) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Movie) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMoviesInterface creates a new instance of moviesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoviesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *moviesInterface {
	mock := &moviesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
