// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	data "github.com/vladgrskkh/movie_recomendation_system/internal/data"
)

// moviesInterface is an autogenerated mock type for the moviesInterface type
type moviesInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *moviesInterface) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFavourite provides a mock function with given fields: movieID, userID
func (_m *moviesInterface) DeleteFavourite(movieID int64, userID int64) error {
	ret := _m.Called(movieID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(movieID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *moviesInterface) Get(id int64) (*data.Movie, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*data.Movie, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *data.Movie); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: title, genres, fileters
func (_m *moviesInterface) GetAll(title string, genres []string, fileters data.Filters) ([]*data.Movie, data.Metadata, error) {
	ret := _m.Called(title, genres, fileters)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*data.Movie
	var r1 data.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(string, []string, data.Filters) ([]*data.Movie, data.Metadata, error)); ok {
		return rf(title, genres, fileters)
	}
	if rf, ok := ret.Get(0).(func(string, []string, data.Filters) []*data.Movie); ok {
		r0 = rf(title, genres, fileters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string, data.Filters) data.Metadata); ok {
		r1 = rf(title, genres, fileters)
	} else {
		r1 = ret.Get(1).(data.Metadata)
	}

	if rf, ok := ret.Get(2).(func(string, []string, data.Filters) error); ok {
		r2 = rf(title, genres, fileters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByIDs provides a mock function with given fields: ids
func (_m *moviesInterface) GetByIDs(ids []int64) ([]*data.Movie, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func([]int64) ([]*data.Movie, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]int64) []*data.Movie); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTitle provides a mock function with given fields: title
func (_m *moviesInterface) GetByTitle(title string) (int64, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for GetByTitle")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNew provides a mock function with given fields: year
func (_m *moviesInterface) GetNew(year int) ([]*data.Movie, error) {
	ret := _m.Called(year)

	if len(ret) == 0 {
		panic("no return value specified for GetNew")
	}

	var r0 []*data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*data.Movie, error)); ok {
		return rf(year)
	}
	if rf, ok := ret.Get(0).(func(int) []*data.Movie); ok {
		r0 = rf(year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopular provides a mock function with no fields
func (_m *moviesInterface) GetPopular() ([]*data.Movie, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPopular")
	}

	var r0 []*data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*data.Movie, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*data.Movie); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWatched provides a mock function with given fields: userID
func (_m *moviesInterface) GetWatched(userID int64) ([]int64, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWatched")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]int64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []int64); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: movie
func (_m *moviesInterface) Insert(movie *data.Movie) error {
	ret := _m.Called(movie)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Movie) error); ok {
		r0 = rf(movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertFavourite provides a mock function with given fields: movieID, userID
func (_m *moviesInterface) InsertFavourite(movieID int64, userID int64) error {
	ret := _m.Called(movieID, userID)

	if len(ret) == 0 {
		panic("no return value specified for InsertFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(movieID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertWatched provides a mock function with given fields: id, userID
func (_m *moviesInterface) InsertWatched(id int64, userID int64) error {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for InsertWatched")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: movie
func (_m *moviesInterface) Update(movie *data.Movie) error {
	ret := _m.Called(movie)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Movie) error); ok {
		r0 = rf(movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMoviesInterface creates a new instance of moviesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoviesInterface(t interface {
	mock.TestingT
	Cleanup(func())
},
) *moviesInterface {
	mock := &moviesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
