// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	data "github.com/vladgrskkh/movie_recomendation_system/internal/data"
)

// recommenderMoviesInterface is an autogenerated mock type for the recommenderMoviesInterface type
type recommenderMoviesInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: userID
func (_m *recommenderMoviesInterface) Get(userID int64) ([]*data.Movie, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*data.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*data.Movie, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []*data.Movie); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: userID, movies
func (_m *recommenderMoviesInterface) Set(userID int64, movies []*data.Movie) error {
	ret := _m.Called(userID, movies)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, []*data.Movie) error); ok {
		r0 = rf(userID, movies)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newRecommenderMoviesInterface creates a new instance of recommenderMoviesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRecommenderMoviesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *recommenderMoviesInterface {
	mock := &recommenderMoviesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
