// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	data "github.com/vladgrskkh/movie_recomendation_system/internal/data"

	time "time"
)

// tokensInterface is an autogenerated mock type for the tokensInterface type
type tokensInterface struct {
	mock.Mock
}

// DeleteAllForUser provides a mock function with given fields: scope, userID
func (_m *tokensInterface) DeleteAllForUser(scope string, userID int64) error {
	ret := _m.Called(scope, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(scope, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: token
func (_m *tokensInterface) Insert(token *data.Token) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// New provides a mock function with given fields: userID, ttl, scope
func (_m *tokensInterface) New(userID int64, ttl time.Duration, scope string) (*data.Token, error) {
	ret := _m.Called(userID, ttl, scope)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *data.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, time.Duration, string) (*data.Token, error)); ok {
		return rf(userID, ttl, scope)
	}
	if rf, ok := ret.Get(0).(func(int64, time.Duration, string) *data.Token); ok {
		r0 = rf(userID, ttl, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, time.Duration, string) error); ok {
		r1 = rf(userID, ttl, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newTokensInterface creates a new instance of tokensInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokensInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *tokensInterface {
	mock := &tokensInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
