name: Backend CI/CD Pipeline 

on:
  push:
    branches:
      - dev/backend
      - development
      - main
  pull_request:
    branches:
      - dev/backend
      - development
      - main

jobs:
  build-test:
    name: 🧪 Build, Migrate, and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mrs
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d mrs"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      MRS_DB_DSN: postgres://postgres:postgres@postgres:5432/mrs?sslmode=disable

    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v4

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: 🧰 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: 📦 Install dependencies
        run: |
          cd backend
          go mod download

      - name: 🗄️ Run database migrations
        uses: docker://migrate/migrate
        with:
          args: >
            -path=/github/workspace/backend/migrations
            -database=${{ env.MRS_DB_DSN }}
            up
        
      - name: Generate Go gRPC code
        run: |
          mkdir -p backend/genproto
          protoc \
            -I=proto \
            --go_out=backend/genproto \
            --go-grpc_out=backend/genproto \
            proto/common/types.proto \
            proto/v1/predict/predict.proto

      - name: ✅ Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          working-directory: backend

      - name: 🧪 Run tests
        run: |
          cd backend
          go test ./... -v

  docker-publish:
    name: 🐳 Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v4

      - name: Generate metadata
        id: meta
        shell: bash
        run: |
          current_time=$(date -Iseconds)
          git_description=$(git describe --always --dirty --tags --long)
          linker_flags="-s -X main.buildTime=${current_time} -X main.version=${git_description}"
          echo "linker_flags=${linker_flags}" >> $GITHUB_OUTPUT

      - name: 🧰 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          build-args: |
            LINKER_FLAGS=${{ steps.meta.outputs.linker_flags}}
          tags: |
            vladgrskkh/mrs-api:latest
            vladgrskkh/mrs-api:${{ github.sha }}

  deploy:
    name: 🚀 Deploy to VPS
    needs: docker-publish
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v4

      - name: Create .env on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            mkdir -p ~/mrs
            mkdir -p ~/mrs/backend
            echo "MRS_DB_DSND=${{ secrets.MRS_DB_DSND }}" > ~/mrs/backend/.env
            echo "SMTP_USERNAMED=${{ secrets.SMTP_USERNAMED }}" >> ~/mrs/backend/.env
            echo "SMTP_PASSWORDD=${{ secrets.SMTP_PASSWORDD }}" >> ~/mrs/backend/.env
            echo "GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}" >> ~/mrs/backend/.env
            echo "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}" >> ~/mrs/backend/.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ~/mrs/backend/.env_db
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ~/mrs/backend/.env_db
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ~/mrs/backend/.env_db


      - name: 🔐 Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          source: "backend/docker-compose.yml,backend/migrations,backend/conf"
          target: "~/mrs/"
          timeout: 120s

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          timeout: 120s
          script: |
            cd ~/mrs/backend
            docker compose pull
            docker compose down
            docker compose up -d --build
            docker system prune -f
