---
name: CD Notification Service Pipeline

on: workflow_dispatch

jobs:
  docker-publish:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./notificationservice
          file: ./notificationservice/Dockerfile
          push: true
          tags: |
            vladgrskkh/mrs-notification-service:latest
            vladgrskkh/mrs-notification-service:${{ github.sha }}

  deploy:
    name: Deploy to VPS
    needs: docker-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST_1 }}
          username: ${{ secrets.VPS_USER_1 }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            mkdir -p ~/kafka
            echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> ~/kafka/.env
            echo "MAILERSEND_API_KEY=${{ secrets.MAILERSEND_API_KEY }}" >> ~/kafka/.env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> ~/kafka/.env
            echo "KAFKA_PASSWORD_SSL=${{ secrets.KAFKA_PASSWORD_SSL }}" >> ~/kafka/.env
            echo "KAFKA_ADDRESS=kafka1:9092" >> ~/kafka/.env
            echo "KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}" >> ~/kafka/.env
            echo "KAFKA_PASSWORD_USER=${{ secrets.KAFKA_PASSWORD_USER }}" >> ~/kafka/.env
            echo "KAFKA_CLUSTER_ID=${{ secrets.KAFKA_CLUSTER_ID }}" >> ~/kafka/.env
            echo "KAFKA_EXTERNAL_ADDRESS=${{ secrets.KAFKA_EXTERNAL_ADDRESS }}" >> ~/kafka/.env
            echo "KAFKA_USERNAME_1=${{ secrets.KAFKA_USERNAME_1 }}" >> ~/kafka/.env
            echo "KAFKA_PASSWORD_1=${{ secrets.KAFKA_PASSWORD_1 }}" >> ~/kafka/.env
            echo "KAFKA_CERT_PASSWORD=${{ secrets.KAFKA_CERT_PASSWORD }}" >> ~/kafka/.env
            echo "KAFKA_KEYSTORE_PASSWORD=${{ secrets.KAFKA_KEYSTORE_PASSWORD }}" >> ~/kafka/.env
            echo "KAFKA_KEY_PASSWORD=${{ secrets.KAFKA_KEY_PASSWORD }}" >> ~/kafka/.env
            echo "KAFKA_TRUSTSTORE_PASSWORD=${{ secrets.KAFKA_TRUSTSTORE_PASSWORD }}" >> ~/kafka/.env
            echo "KAFKAUI_USERNAME=${{ secrets.KAFKAUI_USERNAME }}" >> ~/kafka/.env
            echo "KAFKAUI_PASSWORD=${{ secrets.KAFKAUI_PASSWORD }}" >> ~/kafka/.env

      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          source: notificationservice/docker-compose.yml,notificationservice/config_prod.yml
          target: ~/kafka
          strip_components: 1  # change to flatten:true when author merge pr
          timeout: 120s

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          timeout: 120s
          script: |-
            cd ~/kafka
            docker compose pull
            docker compose down
            docker compose up -d --build
            docker system prune -f
