---
name: CI Image Service Pipeline

on:
  push:
    branches: [dev/image-service, development]
  pull_request:
    branches: [dev/image-service, development]

jobs:
  build-test:
    name: run Test and Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: |
          cd imageservice 
          go mod download

      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          working-directory: imageservice

      - name: Run tests
        run: |-
          cd imageservice 
          go test ./... -v
